### ISSUE TITLE
動作仕様について

### ISSUE THREAD

**Issue by notfdted** [Midra429/NCOverlay#2]
### 詳細

動画によって操作パネルの「A,B」ボタンがグレーアウトで機能しませんが、どのような基準で動作するのでしょうか？

**Comment by Midra429** [comment]
https://github.com/Midra429/NCOverlay/blob/5e20e988a641963e2ef4033bdb76c93b76d10cf4/src/ncoverlay/searcher.ts#L405
1. コメントを5秒間隔で区切る
2. 「A」や「B」が3回以上ヒットした場所を探す
3. その中からヒット数が一番多い場所を基準点にする

という処理になっています。

ただこの方法だと、区切った位置によってはうまくヒットしないので改善予定です。
「A」や「B」のコメントを基準に、以降5秒間のヒット数を元に算出しようかと考えています。

**Comment by Midra429** [comment]
d35ea383553868f4b0704c2c3dc7c0e6e85d433b
